/**
 * Dataset de emojis do IconPicker.
 *
 * Curado à mão em vez de uma lib de emoji (as menores passam de 500KB de JSON):
 * cobre o que se usa em notas, com palavras-chave em PT e EN para a busca.
 * `e` = emoji, `k` = termos de busca.
 */
export type Emoji = { e: string; k: string };
export type EmojiGroup = { name: string; items: Emoji[] };

export const EMOJI_GROUPS: EmojiGroup[] = [
  {
    name: 'Destaques',
    items: [
      { e: '💡', k: 'ideia lampada luz light idea dica tip' },
      { e: '⚠️', k: 'aviso atencao warning alerta cuidado' },
      { e: '🚨', k: 'alerta sirene emergencia alarm urgente' },
      { e: '❗', k: 'importante exclamacao atencao important' },
      { e: '❓', k: 'duvida pergunta question ajuda' },
      { e: '✅', k: 'ok certo feito done check sucesso' },
      { e: '☑️', k: 'checkbox marcado tarefa task' },
      { e: '❌', k: 'errado erro nao x cancel wrong' },
      { e: '🚫', k: 'proibido bloqueado nao forbidden' },
      { e: '🔥', k: 'fogo urgente hot quente prioridade' },
      { e: '⭐', k: 'estrela favorito star importante' },
      { e: '🌟', k: 'brilho destaque star sparkle' },
      { e: '📌', k: 'pin fixar alfinete importante' },
      { e: '📎', k: 'anexo clipe attachment' },
      { e: '🎯', k: 'alvo meta objetivo target goal' },
      { e: '🏁', k: 'meta fim final flag chegada' },
      { e: '🔔', k: 'notificacao sino lembrete bell' },
      { e: '⏰', k: 'alarme hora relogio prazo deadline' },
      { e: '📢', k: 'anuncio megafone aviso announce' },
      { e: '💬', k: 'comentario balao chat mensagem' },
      { e: '🧠', k: 'cerebro ideia mente brain pensar' },
      { e: '📖', k: 'livro aberto leitura doc referencia' },
      { e: '🔑', k: 'chave key senha acesso' },
      { e: '🔒', k: 'trava cadeado seguro lock privado' },
      { e: '♻️', k: 'reciclar refatorar reuso recycle' },
      { e: '🚧', k: 'obra wip em progresso construction' },
      { e: '✂️', k: 'cortar tesoura recortar cut' },
      { e: '➡️', k: 'seta direita next proximo arrow' },
    ],
  },
  {
    name: 'Trabalho & Arquivos',
    items: [
      { e: '📝', k: 'nota anotacao escrever note memo' },
      { e: '📄', k: 'documento pagina arquivo doc page' },
      { e: '📃', k: 'papel documento rolo scroll' },
      { e: '🗒️', k: 'bloco notas notepad' },
      { e: '📋', k: 'prancheta clipboard lista' },
      { e: '🗂️', k: 'pasta divisoria organizar folder' },
      { e: '📁', k: 'pasta folder diretorio' },
      { e: '📂', k: 'pasta aberta folder open' },
      { e: '🗃️', k: 'arquivo caixa fichario archive' },
      { e: '📚', k: 'livros biblioteca docs library' },
      { e: '📊', k: 'grafico barras chart dados' },
      { e: '📈', k: 'crescimento alta grafico growth' },
      { e: '📉', k: 'queda baixa grafico decline' },
      { e: '🧾', k: 'recibo nota fiscal receipt fatura' },
      { e: '💰', k: 'dinheiro money grana saco' },
      { e: '💵', k: 'nota dinheiro dollar cash' },
      { e: '💳', k: 'cartao credito card pagamento' },
      { e: '🏦', k: 'banco bank instituicao' },
      { e: '🗓️', k: 'calendario agenda data calendar' },
      { e: '📅', k: 'calendario data dia date' },
      { e: '⏳', k: 'ampulheta tempo esperando pending' },
      { e: '🕐', k: 'relogio hora time clock' },
      { e: '✍️', k: 'escrever assinar write assinatura' },
      { e: '🖊️', k: 'caneta pen escrever' },
      { e: '📤', k: 'enviar saida outbox upload' },
      { e: '📥', k: 'receber entrada inbox download' },
      { e: '🏷️', k: 'etiqueta tag label' },
      { e: '🔖', k: 'marcador bookmark salvar' },
    ],
  },
  {
    name: 'Tecnologia',
    items: [
      { e: '💻', k: 'notebook laptop computador dev code' },
      { e: '🖥️', k: 'monitor desktop computador pc' },
      { e: '⌨️', k: 'teclado keyboard digitar' },
      { e: '🖱️', k: 'mouse click' },
      { e: '📱', k: 'celular telefone mobile app phone' },
      { e: '🤖', k: 'robo bot ia ai automacao' },
      { e: '⚙️', k: 'config engrenagem settings ajuste' },
      { e: '🛠️', k: 'ferramentas tools manutencao' },
      { e: '🔧', k: 'chave inglesa fix conserto wrench' },
      { e: '🔨', k: 'martelo build construir hammer' },
      { e: '🧩', k: 'peca puzzle modulo plugin' },
      { e: '🧪', k: 'teste laboratorio test experimento' },
      { e: '🐛', k: 'bug erro inseto defeito' },
      { e: '🕸️', k: 'teia web rede grafo graph' },
      { e: '🌐', k: 'web internet global site www' },
      { e: '📡', k: 'antena sinal api rede' },
      { e: '🔌', k: 'plug conectar integracao' },
      { e: '🔋', k: 'bateria energia battery' },
      { e: '💾', k: 'disquete salvar save backup' },
      { e: '💿', k: 'disco cd midia' },
      { e: '🗄️', k: 'arquivo banco database servidor' },
      { e: '🖨️', k: 'impressora print' },
      { e: '📷', k: 'camera foto screenshot' },
      { e: '🎥', k: 'video filmadora gravar' },
      { e: '🔍', k: 'buscar lupa search procurar' },
      { e: '🐳', k: 'docker baleia container whale' },
      { e: '🐍', k: 'python cobra snake' },
      { e: '☁️', k: 'nuvem cloud servidor deploy' },
    ],
  },
  {
    name: 'Pessoas',
    items: [
      { e: '🙂', k: 'sorriso feliz smile' },
      { e: '😀', k: 'feliz risada grin happy' },
      { e: '😅', k: 'alivio suor nervoso sweat' },
      { e: '🤔', k: 'pensando duvida think hmm' },
      { e: '😎', k: 'legal oculos cool' },
      { e: '🥳', k: 'festa comemorar party' },
      { e: '😴', k: 'dormindo sono sleep' },
      { e: '😤', k: 'irritado forca frustrado' },
      { e: '😱', k: 'susto medo scream panico' },
      { e: '🤝', k: 'acordo aperto maos deal parceria' },
      { e: '👍', k: 'ok positivo like aprovado thumbs' },
      { e: '👎', k: 'negativo dislike reprovado' },
      { e: '👏', k: 'palmas parabens clap' },
      { e: '🙏', k: 'obrigado por favor please thanks' },
      { e: '💪', k: 'forca musculo strong esforco' },
      { e: '👀', k: 'olhos revisar ver eyes atencao' },
      { e: '👉', k: 'aponta direita point' },
      { e: '☝️', k: 'aponta cima nota observacao' },
      { e: '👨‍💻', k: 'dev programador developer trabalho' },
      { e: '👩‍💻', k: 'dev programadora developer trabalho' },
      { e: '🧑‍🔧', k: 'tecnico mecanico suporte' },
      { e: '🧑‍🏫', k: 'professor ensinar teach aula' },
      { e: '🕵️', k: 'detetive investigar debug' },
      { e: '👤', k: 'usuario perfil user pessoa' },
      { e: '👥', k: 'grupo equipe team usuarios' },
      { e: '🦸', k: 'heroi hero super' },
      { e: '🧘', k: 'calma meditar zen foco' },
      { e: '🏃', k: 'correndo rapido run sprint' },
    ],
  },
  {
    name: 'Objetos & Casa',
    items: [
      { e: '🏠', k: 'casa home inicio' },
      { e: '🏢', k: 'empresa escritorio office predio' },
      { e: '🏗️', k: 'construcao obra building' },
      { e: '🛒', k: 'compras carrinho mercado cart' },
      { e: '🎁', k: 'presente gift bonus' },
      { e: '📦', k: 'caixa pacote package entrega' },
      { e: '🧰', k: 'caixa ferramentas toolbox' },
      { e: '🪑', k: 'cadeira movel' },
      { e: '🛏️', k: 'cama dormir sono' },
      { e: '🚪', k: 'porta entrada saida door' },
      { e: '🧹', k: 'limpar vassoura clean faxina' },
      { e: '🧺', k: 'cesto roupa lavanderia' },
      { e: '💊', k: 'remedio medicamento saude pill' },
      { e: '🩺', k: 'saude medico consulta health' },
      { e: '🚗', k: 'carro veiculo car transporte' },
      { e: '🏍️', k: 'moto motocicleta' },
      { e: '🚌', k: 'onibus transporte bus' },
      { e: '✈️', k: 'aviao viagem voo travel' },
      { e: '🚀', k: 'foguete lancar deploy launch' },
      { e: '⛽', k: 'combustivel gasolina posto' },
      { e: '🎵', k: 'musica som music audio' },
      { e: '🎨', k: 'arte design paleta cores' },
      { e: '🎮', k: 'jogo game controle' },
      { e: '🏋️', k: 'academia treino gym exercicio' },
      { e: '⚽', k: 'futebol esporte bola soccer' },
      { e: '🎬', k: 'cinema filme claquete video' },
      { e: '🖼️', k: 'imagem quadro foto picture' },
      { e: '🗺️', k: 'mapa roadmap plano map' },
    ],
  },
  {
    name: 'Comida & Natureza',
    items: [
      { e: '☕', k: 'cafe coffee pausa' },
      { e: '🍺', k: 'cerveja beer bar' },
      { e: '🍷', k: 'vinho wine' },
      { e: '🥤', k: 'refrigerante bebida drink' },
      { e: '💧', k: 'agua gota water' },
      { e: '🍔', k: 'hamburguer lanche comida food' },
      { e: '🍕', k: 'pizza comida food' },
      { e: '🍟', k: 'batata frita fries' },
      { e: '🍎', k: 'maca fruta apple' },
      { e: '🍌', k: 'banana fruta' },
      { e: '🥗', k: 'salada saudavel comida' },
      { e: '🍞', k: 'pao bread padaria' },
      { e: '🍫', k: 'chocolate doce' },
      { e: '🎂', k: 'bolo aniversario cake' },
      { e: '🌱', k: 'planta muda crescer seed' },
      { e: '🌳', k: 'arvore natureza tree' },
      { e: '🌵', k: 'cacto planta' },
      { e: '🌸', k: 'flor primavera flower' },
      { e: '🍀', k: 'sorte trevo luck' },
      { e: '🌍', k: 'mundo terra global planeta' },
      { e: '🌙', k: 'lua noite moon dark' },
      { e: '☀️', k: 'sol dia claro sun light' },
      { e: '⛈️', k: 'tempestade chuva storm' },
      { e: '❄️', k: 'neve frio gelado snow' },
      { e: '🌈', k: 'arco iris rainbow' },
      { e: '🐶', k: 'cachorro dog pet' },
      { e: '🐱', k: 'gato cat pet' },
      { e: '🦊', k: 'raposa fox' },
    ],
  },
  {
    name: 'Símbolos',
    items: [
      { e: '🔴', k: 'vermelho circulo red bolinha' },
      { e: '🟠', k: 'laranja circulo orange' },
      { e: '🟡', k: 'amarelo circulo yellow' },
      { e: '🟢', k: 'verde circulo green ok' },
      { e: '🔵', k: 'azul circulo blue' },
      { e: '🟣', k: 'roxo circulo purple' },
      { e: '⚫', k: 'preto circulo black' },
      { e: '⚪', k: 'branco circulo white' },
      { e: '🟥', k: 'quadrado vermelho red square' },
      { e: '🟩', k: 'quadrado verde green square' },
      { e: '🟦', k: 'quadrado azul blue square' },
      { e: '🟨', k: 'quadrado amarelo yellow square' },
      { e: '❤️', k: 'coracao amor love heart' },
      { e: '💙', k: 'coracao azul blue heart' },
      { e: '💚', k: 'coracao verde green heart' },
      { e: '💜', k: 'coracao roxo purple heart' },
      { e: '✨', k: 'brilho novo sparkles novidade' },
      { e: '⚡', k: 'raio rapido energia fast' },
      { e: '💥', k: 'explosao impacto boom' },
      { e: '♦️', k: 'diamante losango' },
      { e: '🔸', k: 'losango pequeno topico bullet' },
      { e: '▶️', k: 'play iniciar executar run' },
      { e: '⏸️', k: 'pausa pause parado' },
      { e: '⏹️', k: 'parar stop' },
      { e: '🔁', k: 'repetir loop ciclo' },
      { e: '🔄', k: 'atualizar sincronizar refresh sync' },
      { e: '⬆️', k: 'seta cima up subir' },
      { e: '⬇️', k: 'seta baixo down descer' },
      { e: '#️⃣', k: 'hashtag numero tag' },
      { e: '∞', k: 'infinito infinity' },
    ],
  },
];

/** Lista plana, para busca e para o botão de aleatório. */
export const ALL_EMOJIS: Emoji[] = EMOJI_GROUPS.flatMap(g => g.items);

/** Remove acentos para a busca casar "codigo" com "código". */
const normalize = (value: string) =>
  value
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '');

export function searchEmojis(query: string): Emoji[] {
  const q = normalize(query.trim());
  if (!q) return [];
  return ALL_EMOJIS.filter(item => normalize(item.k).includes(q) || item.e === query.trim());
}
